version: '3'

networks:
  my-app-network:
    external: true
    ipam:
      config:
        - subnet: 172.16.238.0/24
        - gateway: 172.16.238.1

services:

  nginx:
    image: nginx:latest
    ports:
      - "82:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - php
    networks:
      my-app-network:
        ipv4_address: 172.16.238.5

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    networks:
      my-app-network:
        ipv4_address: 172.16.238.15